<a href="https://colab.research.google.com/github/Sanyam0101/PYTHON-data-SCIENCE-NOTEBOOKS/blob/main/pandas%20data%20manipulations%20and%20filtering%20on%20a%20real%20dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

# Load a sample dataset
df = sns.load_dataset('titanic')

# Display the first 5 rows
print("Original DataFrame:")
display(df.head())

# Perform some data manipulations
# Drop the 'deck' column as it has many missing values
df = df.drop('deck', axis=1)

# Fill missing values in 'age' with the median
df['age'] = df['age'].fillna(df['age'].median())

# Fill missing values in 'embarked' with the most frequent value
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

# Perform some filtering
# Filter for passengers who survived
survived_df = df[df['survived'] == 1]

# Filter for female passengers in the first class
female_first_class_df = df[(df['sex'] == 'female') & (df['pclass'] == 1)]

print("\nDataFrame after dropping 'deck' and filling missing values:")
display(df.head())

print("\nDataFrame of survived passengers:")
display(survived_df.head())

print("\nDataFrame of female passengers in first class:")
display(female_first_class_df.head())

Original DataFrame:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

DataFrame after dropping 'deck' and filling missing values:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

DataFrame of survived passengers:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,Cherbourg,yes,False

DataFrame of female passengers in first class:

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,Southampton,yes,True
31,1,1,female,28.0,1,0,146.5208,C,First,woman,False,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,Cherbourg,yes,False